language: node_js
node_js:
  - '10'
before_script:
  - npm ci
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: gulp build-prod
cache:
  yarn: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
